### ISSUE TITLE
Maintaining

### ISSUE THREAD

**Issue by satsen** [GuyPaddock/JStratum#2]
I've forked this project, updated the dependencies and cleaned it up (https://github.com/Satergo/JStratum). As you do not seem to work on this anymore, I would like to request you to transfer the entire project to me instead, this way it would be simpler for interested developers to find the "newer" project. If you don't want to, maybe I can make a pull request with my changes, or remove the relation between my fork and this project.

**Comment by satsen** [comment]
@GuyPaddock

**Comment by GuyPaddock** [comment]
@satsen Thank you for the request! I will review and circle back this week.

**Comment by satsen** [comment]
@GuyPaddock Have you decided?

**Comment by GuyPaddock** [comment]
@satsen I had sent you an invite to add you as a collaborator but you never accepted. For now, I'd say just fork the project and you can maintain it from your copy.

**Comment by satsen** [comment]
I don't check my mail very often.
